#!/bin/bash

LOCATION=/home/developer/repos/watergo
APP=/applications/watergo
VENVDIR='venv'

if [ ! -d $APP ]; then
    echo $APP - Does NOT exists
    git clone $LOCATION $APP
    cd $APP
    git remote add upstream $LOCATION
    git branch --set-upstream-to=upstream/master
else
    echo $APP - Folder exists:
    cd $APP
    pwd
    git pull
fi

if [ ! -d $VENVDIR ]; then
    # Virtual Env
    virtualenv $VENVDIR
fi

source ./venv/bin/activate

pip install -r requirements.txt

cp `ls -1 dumps/* | head -1` flaskr.db


cp $APP'/hooks/'* $LOCATION'/hooks/'
